# Generated by Django 5.1.5 on 2025-06-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('other', 'Other')], default='other', help_text='Classify project as Primary, Secondary, or Other', max_length=20),
        ),
    ]
